### ISSUE TITLE
CS-Script Hangs Sublime Text for a Few Seconds

### ISSUE THREAD

**Issue by mmickael** [oleg-shilo/cs-script-sublime#1]
Sublime freezes for a few seconds at startup when CS-Script is installed.   Looks like this is caused by loading syntaxer.exe at startup but I am not 100% sure.  Sublime version is 3143.  Cs-Script version 1.2.6.

**Comment by oleg-shilo** [comment]
Thank you for reporting it.

I was trying to avoid any loading penalties. That's why all syntaxer loading operations are asynchronous. E.g. `popen` is never followed by `wait`.

Anyway, I cannot detect any delays in my environment so I added some prints for loading stats. I hope you wouldn't mind to run the [updated version](https://github.com/oleg-shilo/cs-script-sublime/blob/master/imports/syntaxer.py) of syntaxer (with new prints).

In my case the loading is very quick. Let's see if you numbers are different.
![image](https://user-images.githubusercontent.com/16729806/32165268-4b786eb6-bdb6-11e7-93f2-88a637222ca5.png)

**Comment by mmickael** [comment]
Oleg,

Thank you for the quick reply.  I tried the updated file.  Here are my results.

syntaxer_dir C:\Programs\Sublime Text 3\Data\Packages\User\cs-script\syntaxer_v1.2.6
> Syntaxer server started: 0.01561594009399414 seconds


I did not notice much improvement in the freezing issue (roughly 2-3 seconds after startup).  I will try to record a startup session to illustrate the issue.

--

Regards,

Medhat Mickael

**Comment by mmickael** [comment]
Oleg,

I think I found the problem.  In the session log, I noticed an error indicating that it could not find the location of “cscs.exe” and will retry in 3 seconds.  I have a portable installation of Sublime so I added the path of cscs.exe to the user setting.

                "cscs_path": "C:\\Programs\\Sublime Text 3\\Data\\Packages\\cs-script-sublime\\bin\\cscs.exe",

And it no longer hangs.  I will close the issue with this explanation in case someone else has the same problem.

--

Regards,

Medhat Mickael
President, Innovative Downhole Solutions
17810 East Hardy Road, Houston, TX 77073
Main: (832) 827-2908                      Fax: (281) 784-2370
Mobile: (713) 503-4221                  www.innovativedhs.com<http://www.innovativedhs.com/>

**Comment by mmickael** [comment]
Issue fixed by specifying the absolute path of cscs.exe in user settings.  This may only apply to portable installation of Sublime Text.

**Comment by oleg-shilo** [comment]
Unfortunately the work around you found is not fixing but I am afraid masking the problem. So I am reopening the issue. At least for now. 

Another important point is that setting cscs_path to the plugin original `cscs.exe` but not to its copy in `User` can cause unpredictable behavior during plugin updates. That's why I advice to revert it and try to solve it in a more direct way. But of course it's your call. 

> I noticed an error indicating that it could not find the location of “cscs.exe” and will retry in 3 seconds.
 
The problem is not about the `cscs.exe` location. In the routine the plugin is trying to connect to the syntaxer server and it is expected to fail (socket exception) the first attempt. The server is not ready just after the start. That's why on error it will delay and try again up to 5 times. 
BTW your "Syntaxer server started" log indicated that you spent practically no time there.

I think problem is somewhere else. Since I cannot detect the problem I would like to ask you to test it again. Please use the latest `cs-script.py` and `imports/*`. I have placed a few changes there that can in fact bring some improvements not only print stats:
- Socket connection is now delayed by 3 seconds so that confusing socket error (with retry) will not happen.  
- `sublime.set_timeout` is replaced with `sublime.set_timeout_async` to avoid potential delays in the main thread.
- Most important one. Handling "settings changed" event is now asynchronous.

Thank you for your help with testing this issue.

**Comment by mmickael** [comment]
Oleg,

This fixed the problem as well. Here is what I did:


  1.  Copied cs-script.py to  \Sublime Text 3\Data\Packages\cs-script-sublime
  2.  Copied imports/* to \Sublime Text 3\Data\Packages\cs-script-sublime\imports
  3.  Removed cscs_path from user settings
  4.  The cscs_path is set to “./cscs.exe” in default settings

There is no more delays.  Console output shows the following:
==================================================================================================================
----------------
cscs.exe:  C:\Programs\Sublime Text 3\Data\Packages\cs-script-sublime\bin\cscs.exe
syntaxer.exe:  C:\Programs\Sublime Text 3\Data\Packages\User\cs-script\syntaxer_v1.2.6\syntaxer.exe
syntaxer port:  18000
syntaxcheck_on_save:  False
server_autostart:  True
----------------
reloading settings Packages/User/cs-script.sublime-settings
Package Control: Skipping automatic upgrade, last run at 2017-10-31 09:17:41, next run at 2017-10-31 10:17:41 or after
> Connected to syntaxer server: 0.0010058879852294922 seconds
> Roslyn preloading done: 0.0005319118499755859 seconds
==================================================================================================================

Thank you for looking into this issue and for the very useful plugin.

--

Regards,

Medhat Mickael

**Comment by oleg-shilo** [comment]
Excellent.
Thank you. for helping me with the testing. Otherwise it was like trying to catch the black cat in the dark room. :)

**Comment by oleg-shilo** [comment]
Done. Please update to Release v1.2.6

**Comment by mmickael** [comment]
Oleg,

I thought the version I was running was already 1.2.6.

--

Regards,

Medhat Mickael

**Comment by oleg-shilo** [comment]
Not exactly. At the time you were testing it the officially released
version was v1.2.5. I only increased the version in the source code in
anticipation of the future release but did not make a new release from it.
It was just a set of files with the fixes under the source control.

Please let me know if somehow it creates any problems. I am OK to just
re-release with the incremented version it if required.

**Comment by mmickael** [comment]
Oleg,

The version that was installed from Package Control before this issue from https://github.com/oleg-shilo/cs-script-sublime.git was 1.2.6<https://github.com/oleg-shilo/cs-script-sublime.git%20was%201.2.6>.  My user settings shows that version as well. I do not think it is an issue.  I can just uninstall it and install it gain.

--

Regards,

Medhat Mickael

**Comment by oleg-shilo** [comment]
Then it is my mistake with GitHub package management. I do prefer to fix it though.
Done. Rereleased the same codebase as v1.2.7.
Thank you.

**Comment by mmickael** [comment]
Thanks.

--

Regards,

Medhat Mickael
